name: tasmota
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  # Helps you discover open ports, devices on subnet and more.
  network_tools: ^4.0.1
  # Library for making HTTP requests.
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
